### ISSUE TITLE
should this still work out of the box?

### ISSUE THREAD

**Issue by justme-1968** [erikhric/ios2mac#2]
should this still work out of the box with xcode 13.2.1 on macOS 12.2 ?

i can start the app and create the menu item but if i click it i get errors like this: 

`Listener received click from macOS`

`2022-02-02 20:08:30.711837+0100 iOS2mac[5498:5033179] validateSessionInfo: bundleID is invalid. Please specify the bundleID for kRTCReportingSessionInfoClientBundleID`

`2022-02-02 20:08:30.712731+0100 iOS2mac[5498:5033956] validateSessionInfo: bundleID is invalid. Please specify the bundleID for kRTCReportingSessionInfoClientBundleID`

`2022-02-02 20:08:30.714779+0100 iOS2mac[5498:5033942] sendMessageWithDictionary: Failed to get remote object proxy: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.apple.rtcreportingd" UserInfo={NSDebugDescription=connection to service named com.apple.rtcreportingd}`

`2022-02-02 20:08:30.714790+0100 iOS2mac[5498:5033943] sendMessageWithDictionary: Failed to get remote object proxy: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.apple.rtcreportingd" UserInfo={NSDebugDescription=connection to service named com.apple.rtcreportingd}`

thanks
  andre

**Comment by erikhric** [comment]
> andre

Hey @justme-1968,
I'll doublecheck and let you know.
Right now I can tell you I experienced connectivity issues to daemon after updating from Big Sur Beta to GM version.
The issue prevented me from running this app from Xcode directly => I had to build with CMD+B and then locate and run produced '.app' file.

It's possible it is just an Xcode bug and it may be resolved in next version.

I'll get back to you once I'll try it myself 🤞

**Comment by justme-1968** [comment]
thanks! very much appreciated.

**Comment by justme-1968** [comment]
could you already find out more?

**Comment by erikhric** [comment]
Hey @justme-1968 , I have 2 projects using this same approach and the second one works just fine. I compared them and all the entitlements, linked libraries and signing is the same. Honestly, I don't know where is the issue, maybe you can follow [my article](https://medium.com/geekculture/use-of-macos-specific-api-in-maccatalyst-apps-and-vice-versa-e7082a007b7c) step by step in a fresh project.

**Comment by justme-1968** [comment]
thanks! that was what i did. i will try to finds out what is going wrong on my side.
